INSERT INTO persons (id, firstname, lastname) VALUES (1, 'Jan', 'Janssen');
INSERT INTO persons (id, firstname, lastname) VALUES (2, 'Piet', 'Pietersen');
INSERT INTO persons (id, firstname, lastname) VALUES (3, 'Kees', 'Klaassen');
INSERT INTO persons (id, firstname, lastname) VALUES (4, 'Jan', 'Klaassen');
INSERT INTO persons (id, firstname, lastname) VALUES (5, 'Kees', 'Janssen');
INSERT INTO persons (id, firstname, lastname) VALUES (6, 'Kees', 'Klaassen');
INSERT INTO persons (id, firstname, lastname) VALUES (7, 'Kees', 'Klaassen');
INSERT INTO persons (id, firstname, lastname) VALUES (8, 'Kees', 'Klaassen');
INSERT INTO persons (id, firstname, lastname) VALUES (9, 'Kees', 'Klaassen');
INSERT INTO persons (id, firstname, lastname) VALUES (10, 'Jan', 'Pietersen');
INSERT INTO addresses (id, street, city, person_id) VALUES (1, 'Kerkstraat', 'Amsterdam', 1);
INSERT INTO addresses (id, street, city, person_id) VALUES (2, 'Amsteleind', 'Amsterdam', 1);
INSERT INTO addresses (id, street, city, person_id) VALUES (3, 'Kerkstraat', 'Oss', 1);
INSERT INTO products (id, name, type, actor, artist) VALUES (1, 'All music', 'CD', '', 'Josh');
INSERT INTO products (id, name, type, actor, artist) VALUES (2, 'Terminator', 'DVD', 'Arnold', '');
INSERT INTO custom (id, value) VALUES (1, 'yes');
INSERT INTO custom (id, value) VALUES (2, 'no');