INSERT INTO persons (firstname, lastname) VALUES ('Jan', 'Janssen');
INSERT INTO persons (firstname, lastname) VALUES ('Piet', 'Pietersen');
INSERT INTO persons (firstname, lastname) VALUES ('Kees', 'Klaassen');
INSERT INTO persons (firstname, lastname) VALUES ('Jan', 'Klaassen');
INSERT INTO persons (firstname, lastname) VALUES ('Kees', 'Janssen');
INSERT INTO persons (firstname, lastname) VALUES ('Kees', 'Klaassen');
INSERT INTO persons (firstname, lastname) VALUES ('Kees', 'Klaassen');
INSERT INTO persons (firstname, lastname) VALUES ('Kees', 'Klaassen');
INSERT INTO persons (firstname, lastname) VALUES ('Kees', 'Klaassen');
INSERT INTO persons (firstname, lastname) VALUES ('Jan', 'Pietersen');
INSERT INTO addresses (street, city, person_id) VALUES ('Kerkstraat', 'Amsterdam', 1);
INSERT INTO addresses (street, city, person_id) VALUES ('Amsteleind', 'Amsterdam', 1);
INSERT INTO addresses (street, city, person_id) VALUES ('Kerkstraat', 'Oss', 1);
INSERT INTO products (name, type, actor, artist) VALUES ('All music', 'CD', '', 'Josh');
INSERT INTO products (name, type, actor, artist) VALUES ('Terminator', 'DVD', 'Arnold', '');
INSERT INTO custom (value) VALUES ('yes');
INSERT INTO custom (value) VALUES ('no');